
CREATE DATABASE VINOS 
DEFAULT CHARACTER SET latin1 
COLLATE latin1_spanish_ci; 

USE VINOS;

-- TABLEs
CREATE TABLE VINOS (
  ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(64) NOT NULL,
  PRECIO FLOAT NULL,
  GRADOS FLOAT NULL, 
  COLOR VARCHAR(32),
  COMENTARIO VARCHAR(512),
  PRIMARY KEY (ID) )
  ENGINE=MyISAM DEFAULT CHARSET=latin1;
  
  -- INSERTs
  INSERT INTO VINOS (NOMBRE, PRECIO, GRADOS, COLOR, COMENTARIO) VALUES
  ('Baigorri, Maceración Carbónica, 2011', 8.10, 14, 'Tinto', 
  'En la localidad de Samaniego (Rioja Alavesa), Jesús Baigorri lidera ...');
   

